### ISSUE TITLE
Package Support

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-atom-ui#20]
:atom: :package: ❤️ 
This epic tracks issues for support implementations of the most popular Atom packages.
I'm happy for any help and improvement suggestions so please feel free to create a PR or report issues.
## 💬  Community
- [x] <img src="https://avatars1.githubusercontent.com/u/933880" width=16 height=16/>  [`build`](https://atom.io/packages/build) by [noseglid](https://github.com/noseglid) (@arcticicestudio, #34, dfebe0c650e1fa482db42336b18a91dd976588fe)
- [x] <img src="https://avatars3.githubusercontent.com/u/2833514" width=16 height=16/>  [`color-picker`](https://atom.io/packages/color-picker) by [thomaslindstrom](https://github.com/thomaslindstrom) (@arcticicestudio, #21, 132eb79589daaff8333d1024708eeed113234d6a)
- [x] <img src="https://avatars0.githubusercontent.com/u/659763" width=16 height=16/>  [`expose`](https://atom.io/packages/expose) by [mrodalgaard](https://github.com/mrodalgaard) (@arcticicestudio, #30, 4e70ed1d5b135aca0da501ce7b30be7da2af5310)
- [x] <img src="https://avatars3.githubusercontent.com/u/6087523" width=16 height=16/>  [`imdone-atom`](https://atom.io/packages/imdone-atom) by [imdone](https://github.com/imdone) (@arcticicestudio, #38, 4214c7fa)
- [x] <img src="https://avatars3.githubusercontent.com/u/7209979" width=16 height=16/>  [`minimap`](https://atom.io/packages/minimap) by [atom-minimap](https://github.com/atom-minimap) (@arcticicestudio, #28, 8ba2bddc3cfba1d549398932864f3dec2e9a4d1c)
- [x] <img src="https://avatars3.githubusercontent.com/u/7209979" width=16 height=16/>  [`minimap-git-diff`](https://atom.io/packages/minimap-git-diff) by [atom-minimap](https://github.com/atom-minimap) (@arcticicestudio, #42, e5251f73)
- [x] <img src="https://avatars0.githubusercontent.com/u/696872" width=16 height=16/>  [`project-manager`](https://atom.io/packages/project-manager) by [danielbrodin](https://github.com/danielbrodin) (@arcticicestudio, #29, 233233ddfce799e976f53597217c52604c40dd37)
- [x] <img src="https://avatars1.githubusercontent.com/u/836375" width=16 height=16/>  [`script`](https://atom.io/packages/script) by [rgbkrk](https://github.com/rgbkrk) (@arcticicestudio, #37, b8f7e87a)
- [x] <img src="https://avatars3.githubusercontent.com/u/25722" width=16 height=16/>  [`tool-bar`](https://atom.io/packages/tool-bar) by [suda](https://github.com/suda) (@arcticicestudio, #41, 010119c6)
## :atom: Core
- [x] [`autocomplete-plus`](https://atom.io/packages/autocomplete-plus) (@arcticicestudio, #22, 44714fd6b2fbc58cd4a9247c236b579870e7a01d)
- [x] [`deprecation-cop`](https://atom.io/packages/deprecation-cop) (@arcticicestudio, #23, e9b9a1b2a3b6eb91d109eef9df99dc4dfe13725f)
- [x] [`markdown-preview`](https://atom.io/packages/markdown-preview) (@arcticicestudio, #27, 11ed42e6539f3e498ff0cef781154f96c1a9db4d)
- [x] [`timecop`](https://atom.io/packages/timecop) (@arcticicestudio, #24, 20653ad84ad1079c9f55f9a40c677a018dabdbe4)

**Comment by arcticicestudio** [comment]
Resolved tasks:
  - [x] <img src="https://avatars3.githubusercontent.com/u/2833514" width=16 height=16/>  [`color-picker`](https://atom.io/packages/color-picker) by [thomaslindstrom](https://github.com/thomaslindstrom)  
Merged in 132eb79589daaff8333d1024708eeed113234d6a.

**Comment by arcticicestudio** [comment]
Resolved tasks:

### <img src="https://avatars0.githubusercontent.com/u/1089146" width=16 height=16/> Core
  - [x] [`markdown-preview`](https://atom.io/packages/markdown-preview)

**Comment by arcticicestudio** [comment]
Resolved tasks:

### Community
  - [x] <img src="https://avatars1.githubusercontent.com/u/933880" width=16 height=16/>  [`build`](https://atom.io/packages/build)

**Comment by arcticicestudio** [comment]
Resolved tasks:

### Community
  - [x] <img src="https://avatars3.githubusercontent.com/u/6087523" width=16 height=16/>  [`imdone-atom`](https://atom.io/packages/imdone-atom)
  - [x] <img src="https://avatars1.githubusercontent.com/u/836375" width=16 height=16/>  [`script`](https://atom.io/packages/script)

**Comment by arcticicestudio** [comment]
Resolved tasks:

### Community
  - [x] <img src="https://avatars3.githubusercontent.com/u/7209979" width=16 height=16/>  [`minimap-git-diff`](https://atom.io/packages/minimap-git-diff)
  - [x] <img src="https://avatars3.githubusercontent.com/u/25722" width=16 height=16/>  [`tool-bar`](https://atom.io/packages/tool-bar)

**Comment by christianstanfield** [comment]
Branch list isn't showing for Atom's Github package
select tag: `class="github-BranchMenuView-item github-BranchMenuView-select input-select"`
<img width="440" alt="screen shot 2017-06-28 at 4 45 07 pm" src="https://user-images.githubusercontent.com/8076138/27661807-5ca20c52-5c21-11e7-8f9b-5032bcd2bc24.png">

**Comment by arcticicestudio** [comment]
@christianstanfield Thanks for your report :+1: 
I've created #67 which adds general support for the new github core package.

**Comment by arcticicestudio** [comment]
Closing this issue now, special styles for many package are now obsolete since the Atom core theme API changed a lot and improved the default behavior on how packages adapt to the enabled theme.
