### ISSUE TITLE
Atom 1.13 Shadow DOM removal

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-atom-ui#49]
Starting from Atom version 1.13, the contents of `atom-text-editor` [elements are no longer encapsulated within a shadow DOM boundary](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html).
This means the `:host` and `::shadow` pseudo-selectors and the `/deep/` combinator selector should be completely removed.
To prevent breakage with existing style sheets, Atom will automatically upgrade selectors for versions less or equal to 1.12.

Currently Atom 1.13 is in the `beta` chanel (`1.13.0.beta6`).
This issue prepares the package for the incoming breaking changes when Atom 1.13 reaches the **stable** channel. It will me merged as soon as the official Atom theme [One Dark Syntax](https://github.com/atom/one-dark-syntax) updates the Atom engine requirement to [`>=1.13`](https://github.com/atom/one-dark-syntax/blob/master/package.json#L13#L14).

The flight manual provides the great migration guide "[Removing Shadow DOM styles](http://flight-manual.atom.io/shadow-dom/sections/removing-shadow-dom-styles)" for package authors to prepare their packages for this breaking change. 

There are also reference pull requests for the Atom Core theme packages [One Dark Syntax](https://github.com/atom/one-dark-syntax/pull/79) and [One Dark UI](https://github.com/atom/one-dark-ui/pull/168).

The associated [`improvement/ghi-#49-atom-1.13-shadow-dom-removal`](https://github.com/arcticicestudio/nord-atom-ui/tree/improvement/ghi-%2349-atom-1.13-shadow-dom-removal) branch will be merged as soon as the versions of the official themes "One Dark UI" and "One Dark Syntax" are bumped to `<=1.13` in their `package.json` files to keep compability as long as lower versions are supported.

**Tasks**
  - [x] Remove all `:host` and `::shadow` pseudo-selectors
  - [x] Remove all `/deep/` combinator selectors

**Known issues/bugs**
  - [x] Bright text color in active text fields broken through the selector removements
  - [x] Bright text field border on hover

**Comment by arcticicestudio** [comment]
🚢 Shipped in apm package release version 🏷 [0.10.0](https://github.com/arcticicestudio/nord-atom-ui/releases/tag/v0.10.0).
