### ISSUE TITLE
Update MIT licensing

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-atom-ui#70]
> Subtask of arcticicestudio/nord#55

Update the MIT license to adapt to the changes of the main [Nord][nord] project. Detailed information can be found in the main task ticket.

### Tasks

* [x] Update all license SVG badges
* [x] Update the `LICENSE.md` content
* [x] Update- and simplify all source code comment header

[nord]: https://github.com/arcticicestudio/nord
